FROM nginx:1.15.8-alpine

LABEL MAINTAINER="Thanat Mathanukraw"

RUN rm /etc/nginx/conf.d/default.conf

COPY /build/ /usr/share/nginx/html
COPY conf.d/app.conf /etc/nginx/conf.d/


EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]